correct the version for meson build
intel/libva pull request #455
Opened 2020-10-09 07:19 UTC by XinfengZhang

Signed-off-by: Carl Zhang <carl.zhang@intel.com>

2020-10-09 07:20 UTC, XinfengZhang commented
it fix #454

2020-10-20 18:20 UTC, dvrogozh requested changes

2020-10-20 18:20 UTC, dvrogozh commented on meson.build
> +  version : '2.9.0',
can you bump the version to become 2.9.1? Just removing ending .0 without bumping the version might cause issues with package managers on version check (which package has greater version 2.9.0 vs. 2.9.0.0).

2020-10-23 19:36 UTC, dvrogozh commented
I think this one will be better: #465

2020-12-03 04:35 UTC, closed without merging