report the capability of vaCopy support
intel/libva pull request #513
Opened 2021-03-31 13:03 UTC by XinfengZhang

Signed-off-by: Carl Zhang <carl.zhang@intel.com>

2021-04-07 15:10 UTC, dvrogozh requested changes

2021-04-07 15:10 UTC, dvrogozh commented on va/va.h
> +    VADisplayAttibCopy                 = 19,
Fix: s/Attib/Attrib/

2021-04-07 15:10 UTC, dvrogozh commented on va/va.h
> + * Display attributes also are used to query/set display adaptor related information
Please, reformulate and add punctuation signs appropriately.

2021-04-07 15:10 UTC, dvrogozh commented on va/va.h
> +     * adaptor / platform attributes. read only. specify whether vaCopy support on current HW
> adaptor / platform attributes.

I don't understand what you mean here.

2021-04-08 05:27 UTC, XinfengZhang commented on va/va.h
> +    VADisplayAttibCopy                 = 19,
yes, thanks

2021-04-08 11:00 UTC, emersion commented on va/va.h
> + * should be marked as "HW attribute" in the discription
Typo: "description"

2021-04-08 11:03 UTC, emersion commented on va/va.h
> + * These attributes does not depend on vaConfig, only related with platform or display adaptor
Typo: "do not"

2021-04-08 11:05 UTC, emersion commented on va/va.h
> + * To distinguish these two types display attributes, this display adaptor related attributres
Typo: "attributes"

2021-04-09 21:55 UTC, dmitryermilov approved these changes

2021-04-26 14:29 UTC, dvrogozh commented on va/va.h
> + * Display attributes also are used to query/set display adaptor (vaDisplay) related information.
Suggest to rewrite:

```
 * Display attributes can also be used to query/set platform or display adaptor (vaDisplay)
 * related information. These attributes do not depend on vaConfig, and could not be used
 * for vaPutSurface. Application can use vaQueryDisplayAttributes/vaGetDisplayAttributes
 * at anytime after vaInitialize, but (for settable attributes) vaSetDisplayAttributes should be
 * called after vaInitialize and before any other function call.
 *
 * To distinguish these two types of display attributes, display adaptor related attributes
 * should be marked as "HW attribute" in the description.
```

2021-04-29 02:35 UTC, dvrogozh approved these changes

2021-06-16 08:31 UTC, merged