meson: set HAVE_VA_X11 when applicable
intel/libva pull request #612
Opened 2022-07-07 23:16 UTC by evelikov

Without the define, we'll end without the Xorg auth whenever the DRM
display is used.

---

Team please consider porting this for the stable releases.
Thanks

2022-07-11 13:36 UTC, evelikov commented
v2: move to va/meson.build, consistently use WITH_X11 (current code uses only x11_dep.found())

2022-07-13 12:05 UTC, evelikov commented
@XinfengZhang @uartie humble ping?

2022-07-15 15:08 UTC, ceyusa commented
otherwise, it looks good and necessary for completeness. I agree on back porting it to stable release.

2022-07-16 13:47 UTC, evelikov commented on va/meson.build
> +      '-DHAVE_X11',
It was correct with v1, but I've butchered with in v2. Thanks o/

2022-08-14 03:50 UTC, dvrogozh requested changes
It seems there is also another issue related to meson x11 path, here:

https://github.com/intel/libva/blob/0a989c9f0af69dcb15253945228c53780f019b79/meson.build#L91

Isn't that a typo: `s/with_glx/with_x11/`?

2022-08-14 17:15 UTC, evelikov commented
> It seems there is also another issue related to meson x11 path, here:
> 
> https://github.com/intel/libva/blob/0a989c9f0af69dcb15253945228c53780f019b79/meson.build#L91
> 
> Isn't that a typo: `s/with_glx/with_x11/`?

Nope, the check is correct - as the error message just below it says.

2022-08-15 02:45 UTC, dvrogozh commented
> > It seems there is also another issue related to meson x11 path, here:
> > https://github.com/intel/libva/blob/0a989c9f0af69dcb15253945228c53780f019b79/meson.build#L91
> > 
> > Isn't that a typo: `s/with_glx/with_x11/`?
> 
> Nope, the check is correct - as the error message just below it says.

Yep. You are right.

2022-08-15 02:46 UTC, dvrogozh approved these changes
looks good

2022-08-15 03:39 UTC, XinfengZhang approved these changes

2022-09-08 22:39 UTC, merged