ci: Add style check
intel/libva pull request #653
Opened 2022-11-19 18:57 UTC by evelikov

Closes: https://github.com/intel/libva/issues/393

Automate things instead of thing it manually as mentioned in https://github.com/intel/libva/pull/631

/cc @sivileri for the dos2unix changes

2022-11-20 03:36 UTC, sivileri commented
The libva-win32 related style changes look good to me

2022-11-21 17:05 UTC, dvrogozh requested changes

2022-11-21 18:50 UTC, evelikov commented on .github/workflows/style.yml
> +          git
Thanks fixed.

2022-11-21 18:58 UTC, dvrogozh approved these changes
looks good

2022-11-22 02:09 UTC, XinfengZhang approved these changes
LGTM, so, first, run astyle , then check whether there are file changed by astyle, and report pass/failed.

2022-11-22 03:09 UTC, merged