Upload a security disclaimer
intel/libva pull request #662
Opened 2022-11-28 08:49 UTC by daleksan

2022-11-29 07:13 UTC, XinfengZhang approved these changes

2022-12-02 13:37 UTC, evelikov commented
AFAICT there is a security section already in [CONTRIBUTING.md](https://github.com/intel/libva/blob/master/CONTRIBUTING.md).

Shouldn't that one be updated or removed? Would it make sense to reference this new file in the [CONTRIBUTING.md](https://github.com/intel/libva/blob/master/CONTRIBUTING.md) or 
[README.md](https://github.com/intel/libva/blob/master/README.md)?

2022-12-02 18:22 UTC, dvrogozh requested changes
> AFAICT there is a security section already in [CONTRIBUTING.md](https://github.com/intel/libva/blob/master/CONTRIBUTING.md).

> Shouldn't that one be updated or removed?

I agree. Before introducing something new check whether this was already handled and if it was - correlate.

2022-12-14 05:43 UTC, XinfengZhang commented
@dvrogozh other concern?

2022-12-16 01:34 UTC, merged