Add trace for vaExportSurfaceHandle
intel/libva pull request #724
Opened 2023-07-03 03:10 UTC by MicroYY

2023-07-05 16:56 UTC, dvrogozh requested changes

2023-07-05 16:56 UTC, dvrogozh commented on va/va_trace.c
> +    va_TraceMsg(trace_ctx, "\tfourcc      = %u\n", desc->fourcc);
This will crash if descriptor is NULL. Parent function (`vaExportSurfaceHandle`) does not check that (and it should not). Add check here, please.

2023-07-05 16:56 UTC, dvrogozh commented on va/va_trace.c
> +}
add empty line in end of file

2023-07-06 02:18 UTC, dvrogozh requested changes

2023-07-06 02:18 UTC, dvrogozh commented on va/va_trace.c
> +    VADRMPRIMESurfaceDescriptor *desc = (VADRMPRIMESurfaceDescriptor *)descriptor;
As noted at
https://github.com/intel/libva/blob/984dfee4177021c400367f5dffc0776a6dd745dc/va/va.h#L4054-L4055

You can't assume it's `VADRMPRIMESurfaceDescriptor` without checking `memType`.

2023-07-11 17:01 UTC, dvrogozh approved these changes
looks good

2023-07-11 17:01 UTC, dvrogozh commented on va/va_trace.c
> +    VADRMPRIMESurfaceDescriptor *desc = (VADRMPRIMESurfaceDescriptor *)descriptor;
Fixed in last version, see line 6337 above.

2023-07-11 17:01 UTC, dvrogozh commented on va/va_trace.c
> +    va_TraceMsg(trace_ctx, "\tfourcc      = %u\n", desc->fourcc);
Fixed in last version, see line 6343 above.

2023-07-12 07:38 UTC, XinfengZhang approved these changes

2023-07-17 03:10 UTC, FurongZhang approved these changes
Looks good to me

2023-07-20 13:38 UTC, merged