Add flag to swap references.
intel/libva pull request #817
Opened 2024-05-23 03:24 UTC by FurongZhang

There are different understanding of forward references(could be past frames or future frames) and backward references (could be past frames or future frames).

This flag allows the user to configure the reference as past or future frames.
     - Value 0: by default, forward_references mean future frames, backward_references mean past frames
     - Value 1: swap, forward_references mean past frames, backward_references mean future frames

2024-05-23 06:27 UTC, XinfengZhang requested changes

2024-05-23 06:27 UTC, XinfengZhang commented on va/va_vpp.h
> +    /** \brief Array of forward reference frames (future frames by default). */
non-backward change

2024-05-24 10:27 UTC, ceyusa commented
would be possible to the driver to ignore the swap request?

2024-05-29 01:20 UTC, FurongZhang commented
> would be possible to the driver to ignore the swap request?

If the application does not need swap, the application can ignore the swap.

2024-09-26 06:59 UTC, closed without merging